name = "TestRunner"
uuid = "4efbe77e-ddf3-4ce7-be91-16409ca9e85f"
version = "0.1.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[deps]
CodeTracking = "84636303-58db-50e9-b60a-55781930faa2"
Compiler = "24462c5c-eae5-5efa-8a3d-a35d8ccd96aa"
JSON = "46009aa5-408a-5993-b482-0512622b8f27"
JuliaInterpreter = "a82ab8a0-b04b-500c-ae1d-6b4e87c3563c"
JuliaSyntax = "6213d419-e26c-57d9-96d0-6998e7acb287"
LoweredCodeUtils = "93a4bf1e-9445-5238-95ce-690001486732"
MacroTools = "90711cde-3a55-5bed-8c91-ff489981721a"
Parsers = "e996d0cc-5495-5f06-b9fe-87f07f942bbe"
PrecompileTools = "34277385-dbfe-5e9c-a5da-1fda53d5b4c9"
Preferences = "a85d3927-2675-5020-995e-8e17f64c82bb"
StructUtils = "c27443c7-5f73-531e-b2b6-c9c0ec3be2c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
CodeTracking = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/CodeTracking", url = "https://github.com/aviatesk/TestRunner.jl"}
Compiler = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/Compiler", url = "https://github.com/aviatesk/TestRunner.jl"}
JSON = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/JSON", url = "https://github.com/aviatesk/TestRunner.jl"}
JuliaInterpreter = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/JuliaInterpreter", url = "https://github.com/aviatesk/TestRunner.jl"}
JuliaSyntax = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/JuliaSyntax", url = "https://github.com/aviatesk/TestRunner.jl"}
LoweredCodeUtils = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/LoweredCodeUtils", url = "https://github.com/aviatesk/TestRunner.jl"}
MacroTools = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/MacroTools", url = "https://github.com/aviatesk/TestRunner.jl"}
Parsers = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/Parsers", url = "https://github.com/aviatesk/TestRunner.jl"}
PrecompileTools = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/PrecompileTools", url = "https://github.com/aviatesk/TestRunner.jl"}
Preferences = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/Preferences", url = "https://github.com/aviatesk/TestRunner.jl"}
StructUtils = {rev = "5d4cca227a0c250bc079d8f37c85532f26b90d2e", subdir = "vendor/StructUtils", url = "https://github.com/aviatesk/TestRunner.jl"}

[compat]
Compiler = "0.1"
JSON = "1.3.0"
JuliaInterpreter = "0.10.3"
JuliaSyntax = "1, 2"
LoweredCodeUtils = "3.3.1"
MacroTools = "0.5.16"
PrecompileTools = "1.3.2"
Test = "1.11"
julia = "1.12"

[apps.testrunner]
